export const BUTTON_VARIANTS = {
  SMALL_WHITE: 'SMALL_WHITE',
  LARGE: 'LARGE',
  LARGE_WHITE: 'LARGE_WHITE',
  LARGE_WHITE_100: 'LARGE_WHITE_100',
  TABLE_MORE: 'TABLE_MORE',
  LARGE_TRANSPARENT: 'LARGE_TRANSPARENT'
};
